// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: tool.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	// 健康
	Status_Health Status = 0
	// 即将损坏
	Status_Waring Status = 1
	// 已经损坏
	Status_Damage Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Health",
		1: "Waring",
		2: "Damage",
	}
	Status_value = map[string]int32{
		"Health": 0,
		"Waring": 1,
		"Damage": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_tool_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_tool_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_tool_proto_rawDescGZIP(), []int{0}
}

type Tool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MachineId int32  `protobuf:"varint,2,opt,name=machineId,proto3" json:"machineId,omitempty"`
	Status    Status `protobuf:"varint,3,opt,name=status,proto3,enum=protos.Status" json:"status,omitempty"`
}

func (x *Tool) Reset() {
	*x = Tool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tool_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_tool_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_tool_proto_rawDescGZIP(), []int{0}
}

func (x *Tool) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tool) GetMachineId() int32 {
	if x != nil {
		return x.MachineId
	}
	return 0
}

func (x *Tool) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Health
}

var File_tool_proto protoreflect.FileDescriptor

var file_tool_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x22, 0x5c, 0x0a, 0x04, 0x54, 0x6f, 0x6f, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x2a, 0x2c, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x61, 0x72, 0x69,
	0x6e, 0x67, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x10, 0x02,
	0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tool_proto_rawDescOnce sync.Once
	file_tool_proto_rawDescData = file_tool_proto_rawDesc
)

func file_tool_proto_rawDescGZIP() []byte {
	file_tool_proto_rawDescOnce.Do(func() {
		file_tool_proto_rawDescData = protoimpl.X.CompressGZIP(file_tool_proto_rawDescData)
	})
	return file_tool_proto_rawDescData
}

var file_tool_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tool_proto_goTypes = []interface{}{
	(Status)(0),  // 0: protos.Status
	(*Tool)(nil), // 1: protos.Tool
}
var file_tool_proto_depIdxs = []int32{
	0, // 0: protos.Tool.status:type_name -> protos.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tool_proto_init() }
func file_tool_proto_init() {
	if File_tool_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tool_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tool_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tool_proto_goTypes,
		DependencyIndexes: file_tool_proto_depIdxs,
		EnumInfos:         file_tool_proto_enumTypes,
		MessageInfos:      file_tool_proto_msgTypes,
	}.Build()
	File_tool_proto = out.File
	file_tool_proto_rawDesc = nil
	file_tool_proto_goTypes = nil
	file_tool_proto_depIdxs = nil
}
