// Code generated by entc, DO NOT EDIT.

package tool

const (
	// Label holds the string label denoting the tool type in the database.
	Label = "tool"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMachineID holds the string denoting the machine_id field in the database.
	FieldMachineID = "machine_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the tool in the database.
	Table = "tools"
)

// Columns holds all SQL columns for tool fields.
var Columns = []string{
	FieldID,
	FieldMachineID,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// MachineIDValidator is a validator for the "machine_id" field. It is called by the builders before save.
	MachineIDValidator func(int) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int
)
