// Code generated by entc, DO NOT EDIT.

package ent

import (
	"boot/ent/notice"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NoticeCreate is the builder for creating a Notice entity.
type NoticeCreate struct {
	config
	mutation *NoticeMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (nc *NoticeCreate) SetCreateTime(t time.Time) *NoticeCreate {
	nc.mutation.SetCreateTime(t)
	return nc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (nc *NoticeCreate) SetNillableCreateTime(t *time.Time) *NoticeCreate {
	if t != nil {
		nc.SetCreateTime(*t)
	}
	return nc
}

// SetUpdateTime sets the "update_time" field.
func (nc *NoticeCreate) SetUpdateTime(t time.Time) *NoticeCreate {
	nc.mutation.SetUpdateTime(t)
	return nc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (nc *NoticeCreate) SetNillableUpdateTime(t *time.Time) *NoticeCreate {
	if t != nil {
		nc.SetUpdateTime(*t)
	}
	return nc
}

// SetNoticeType sets the "noticeType" field.
func (nc *NoticeCreate) SetNoticeType(i int) *NoticeCreate {
	nc.mutation.SetNoticeType(i)
	return nc
}

// SetUserId sets the "userId" field.
func (nc *NoticeCreate) SetUserId(i int) *NoticeCreate {
	nc.mutation.SetUserId(i)
	return nc
}

// SetContent sets the "content" field.
func (nc *NoticeCreate) SetContent(s string) *NoticeCreate {
	nc.mutation.SetContent(s)
	return nc
}

// Mutation returns the NoticeMutation object of the builder.
func (nc *NoticeCreate) Mutation() *NoticeMutation {
	return nc.mutation
}

// Save creates the Notice in the database.
func (nc *NoticeCreate) Save(ctx context.Context) (*Notice, error) {
	var (
		err  error
		node *Notice
	)
	nc.defaults()
	if len(nc.hooks) == 0 {
		if err = nc.check(); err != nil {
			return nil, err
		}
		node, err = nc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NoticeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = nc.check(); err != nil {
				return nil, err
			}
			nc.mutation = mutation
			node, err = nc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(nc.hooks) - 1; i >= 0; i-- {
			mut = nc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (nc *NoticeCreate) SaveX(ctx context.Context) *Notice {
	v, err := nc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (nc *NoticeCreate) defaults() {
	if _, ok := nc.mutation.CreateTime(); !ok {
		v := notice.DefaultCreateTime()
		nc.mutation.SetCreateTime(v)
	}
	if _, ok := nc.mutation.UpdateTime(); !ok {
		v := notice.DefaultUpdateTime()
		nc.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nc *NoticeCreate) check() error {
	if _, ok := nc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New("ent: missing required field \"create_time\"")}
	}
	if _, ok := nc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New("ent: missing required field \"update_time\"")}
	}
	if _, ok := nc.mutation.NoticeType(); !ok {
		return &ValidationError{Name: "noticeType", err: errors.New("ent: missing required field \"noticeType\"")}
	}
	if _, ok := nc.mutation.UserId(); !ok {
		return &ValidationError{Name: "userId", err: errors.New("ent: missing required field \"userId\"")}
	}
	if _, ok := nc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New("ent: missing required field \"content\"")}
	}
	return nil
}

func (nc *NoticeCreate) sqlSave(ctx context.Context) (*Notice, error) {
	_node, _spec := nc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (nc *NoticeCreate) createSpec() (*Notice, *sqlgraph.CreateSpec) {
	var (
		_node = &Notice{config: nc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: notice.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: notice.FieldID,
			},
		}
	)
	if value, ok := nc.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notice.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := nc.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notice.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if value, ok := nc.mutation.NoticeType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: notice.FieldNoticeType,
		})
		_node.NoticeType = value
	}
	if value, ok := nc.mutation.UserId(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: notice.FieldUserId,
		})
		_node.UserId = value
	}
	if value, ok := nc.mutation.Content(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notice.FieldContent,
		})
		_node.Content = value
	}
	return _node, _spec
}

// NoticeCreateBulk is the builder for creating many Notice entities in bulk.
type NoticeCreateBulk struct {
	config
	builders []*NoticeCreate
}

// Save creates the Notice entities in the database.
func (ncb *NoticeCreateBulk) Save(ctx context.Context) ([]*Notice, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ncb.builders))
	nodes := make([]*Notice, len(ncb.builders))
	mutators := make([]Mutator, len(ncb.builders))
	for i := range ncb.builders {
		func(i int, root context.Context) {
			builder := ncb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NoticeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ncb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ncb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ncb *NoticeCreateBulk) SaveX(ctx context.Context) []*Notice {
	v, err := ncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
