// Code generated by entc, DO NOT EDIT.

package ent

import (
	"boot/ent/notice"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// Notice is the model entity for the Notice schema.
type Notice struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// NoticeType holds the value of the "noticeType" field.
	NoticeType int `json:"noticeType,omitempty"`
	// UserId holds the value of the "userId" field.
	UserId int `json:"userId,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Notice) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case notice.FieldID, notice.FieldNoticeType, notice.FieldUserId:
			values[i] = new(sql.NullInt64)
		case notice.FieldContent:
			values[i] = new(sql.NullString)
		case notice.FieldCreateTime, notice.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Notice", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Notice fields.
func (n *Notice) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notice.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			n.ID = int(value.Int64)
		case notice.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				n.CreateTime = value.Time
			}
		case notice.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				n.UpdateTime = value.Time
			}
		case notice.FieldNoticeType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field noticeType", values[i])
			} else if value.Valid {
				n.NoticeType = int(value.Int64)
			}
		case notice.FieldUserId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field userId", values[i])
			} else if value.Valid {
				n.UserId = int(value.Int64)
			}
		case notice.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				n.Content = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Notice.
// Note that you need to call Notice.Unwrap() before calling this method if this Notice
// was returned from a transaction, and the transaction was committed or rolled back.
func (n *Notice) Update() *NoticeUpdateOne {
	return (&NoticeClient{config: n.config}).UpdateOne(n)
}

// Unwrap unwraps the Notice entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (n *Notice) Unwrap() *Notice {
	tx, ok := n.config.driver.(*txDriver)
	if !ok {
		panic("ent: Notice is not a transactional entity")
	}
	n.config.driver = tx.drv
	return n
}

// String implements the fmt.Stringer.
func (n *Notice) String() string {
	var builder strings.Builder
	builder.WriteString("Notice(")
	builder.WriteString(fmt.Sprintf("id=%v", n.ID))
	builder.WriteString(", create_time=")
	builder.WriteString(n.CreateTime.Format(time.ANSIC))
	builder.WriteString(", update_time=")
	builder.WriteString(n.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", noticeType=")
	builder.WriteString(fmt.Sprintf("%v", n.NoticeType))
	builder.WriteString(", userId=")
	builder.WriteString(fmt.Sprintf("%v", n.UserId))
	builder.WriteString(", content=")
	builder.WriteString(n.Content)
	builder.WriteByte(')')
	return builder.String()
}

// Notices is a parsable slice of Notice.
type Notices []*Notice

func (n Notices) config(cfg config) {
	for _i := range n {
		n[_i].config = cfg
	}
}
