// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Machine is the predicate function for machine builders.
type Machine func(*sql.Selector)

// Notice is the predicate function for notice builders.
type Notice func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Tool is the predicate function for tool builders.
type Tool func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
